### PR TITLE
Added IRI to contrib

### PR DESCRIPTION
**Pull request by kelvinhammond**

### CODE REVIEW

**Comment by kelvinhammond** [comment]
Not sure what to set the copyright to, please advise.

**Comment by ColinH** [comment]
Could the first `sor` be changed to use `ranges` instead? Otherwise looks good, except perhaps for some minor formatting that we can fix later.

**Comment by kelvinhammond** [comment]
It could be but this formatted better, i have a version of this with that,
what do you prefer?

**Comment by d-frey** [comment]
Using `ranges<...>` is more efficient than using `sor<range<...>,range<...>,...>`, so the former is preferred.

**Comment by d-frey** [comment]
For the copyright: For now, just go with the current header - I'll change it later when hopefully all contributors agreed to the license change.

For the formatting: We'll take care of that, don't worry about it too much.

**Comment by kelvinhammond** [comment]
Updated

**Pull request merged**
