### PR TITLE
Fix Android CI builds

### PR DESCRIPTION
**Pull request by Bjoe**
This is a proposal to fix failing android CI builds. See issue #216 

It uses a docker where the android NDK r22 beta 1 is installed to build PEGTL.

See also travis build: https://travis-ci.org/github/Bjoe/PEGTL/jobs/745332637

It needs maybe some "cleanup" regarding to the output.

Maybe some output of the current NDK/SDK version would be useful.

### CODE REVIEW

**Comment by Bjoe** [comment]
Let me introduce some output like: NDK version etc and maybe some other improvement. Give me some days.I will notice you if I'm done.

**Comment by Bjoe** [comment]
It is more or less done. 
See travis build: https://travis-ci.org/github/taocpp/PEGTL/jobs/747196414

There is "error" 
```
ls: cannot access '/opt/androidSdk/platforms': Operation not permitted
-- ANDROID_PLATFORM not set. Defaulting to minimum supported version
16.
```
I didn't understand yet why this happens, because when I use the docker "localy" I didn't get this errors ....
But at least, PEGTL builds without any build errors so it does not harm the build. It would be nice to merge this and I will investigate deeper what are the problems on travis. But I think you know that is a time consumption task :-)

Btw. I use the docker approach because:
* It is not always downloading and installing the NDK/SDK stuff so it should be faster as before?! Not 100% sure because unfortunately the docker image is also always downloading. I expected that they only downloaded once ...
* It will not break your build because of some changes (for example, maybe there change the path for cmake etc) in the NDK/SDK  or because of some now license agreements etc etc. 
* But the biggest reason is because of maintenance. If there are problems, I or you can take the docker and build PEGTL for android without installing some SDK/NDK locally on your machine etc. 
The command to build PEGTL localy for android is:
```
cd [TO_PEGTL_SOURCES]
docker run -it --rm -v `pwd`:/source bojoe/cpp-android-ndk-build-env-ubuntu:r22beta1 "cmake -H/source -B/home/developer/build -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/androidSdk/ndk/android-ndk-r22-beta1/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-26 -DCMAKE_BUILD_TYPE=Release -DPEGTL_BUILD_EXAMPLES=OFF && cmake --build /home/developer/build --target all"
```
See also in `.travis.yml`
You can also "manually" build and debug the build in the docker:
```
docker run -it --rm -v `pwd`:/source bojoe/cpp-android-ndk-build-env-ubuntu:r22beta1 "/bin/bash"
```
or
```
docker run -it --rm -v `pwd`:/source bojoe/cpp-android-ndk-build-env-ubuntu:r22beta1 "cmake -H/source -B/home/developer/build -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/androidSdk/ndk/android-ndk-r22-beta1/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-26 -DCMAKE_BUILD_TYPE=Release -DPEGTL_BUILD_EXAMPLES=OFF && /bin/bash"
```
You will find the sources in the docker in `/source` .... but you can change this with the docker parameter `-v` ....

When there is a new NDK out, I will create a new docker on the docker hub and "tag" it with the new version. See https://hub.docker.com/r/bojoe/cpp-android-ndk-build-env-ubuntu
The docker sources are here:
https://github.com/Bjoe/DockerImages  
if you see I build some more docker environment also for other project because I always take an docker to develop and build .... :-). So I can use the latest ore newest compiler for everything without to mess up my host system ;-)

**Comment by d-frey** [comment]
Thanks @Bjoe !

Some points for the future (some of which you already mentioned):
* Show the output from the compile just like with other jobs.
* Run the tests.
* Move those jobs to GitHub Actions.
* Now that we have fallbacks for std::experimental::filesystem: Maybe older Android versions are now able to use the PEGTL again? Could you check, please?

For moving stuff to GitHub Actions: I've seen that conanio hat some images for Android. I have no idea if that helps, but in our main-ci.yml there is a link to https://github.com/conan-io/conan-docker-tools where they list Android images. If those images are not suitable, you could probably still use your image with a job in our GitHub Actions main-ci.yml.

**Comment by Bjoe** [comment]
@d-frey 

> * Show the output from the compile just like with other jobs.
> 
> * Run the tests.
> 
> * Move those jobs to GitHub Actions.
> 
> * Now that we have fallbacks for std::experimental::filesystem: Maybe older Android versions are now able to use the PEGTL again? Could you check, please?

Yep, it is possible and that's my idea.

I created some task on my story board ... I will start soon ....see https://github.com/Bjoe/PEGTL/projects/1

**Comment by Bjoe** [comment]
@d-frey 

> For moving stuff to GitHub Actions: I've seen that conanio hat some images for Android. I have no idea if that helps, but in our main-ci.yml there is a link to https://github.com/conan-io/conan-docker-tools where they list Android images. If those images are not suitable, you could probably still use your image with a job in our GitHub Actions main-ci.yml.

Ok. I also involved in the [hunter project ](https://github.com/cpp-pm/hunter/pull/316) and there we use also "GitHub Actions" .... let me see what I can found out... but step by step.
First, I will also update [PEGTL in hunter](https://github.com/cpp-pm/hunter/tree/master/cmake/projects/pegtl) then I can see what are working on Github Actions build :-)

**Pull request merged**
