### PR TITLE
add msys2 CI

### LINKED ISSUE #365: MSYS2 environment is not considered in tests
3 Tests fail on msys, since wrong file names are used in those cases.

`src/test/pegtl/file_file.cpp`
`src/test/pegtl/file_mmap.cpp`
`src/test/pegtl/file_read.cpp`

In this code MSYS isn't considered and handled incorrectly

`src/test/pegtl/verify_file.hpp:11`
```cpp
#if defined( _MSC_VER )
#define TAO_PEGTL_TEST_FILENAME u"src/test/pegtl/file_äöü𝄞_data.txt"
#else
#define TAO_PEGTL_TEST_FILENAME "src/test/pegtl/file_äöü𝄞_data.txt"
#endif
```

I think fixing this is easy, just detect msys2 and use the correct string format there.

See e.g. [this CI run](https://github.com/mesonbuild/wrapdb/actions/runs/10333226401/job/28605345845) as example

### PR DESCRIPTION
**Pull request by Totto16**
This adds a [Msys2](https://www.msys2.org/) CI.

I tested it in Msys2 Clang64 locally and fixed #365 too.
For that I also had to change some code, so that Msys2 uses windows wide string functions to open a file, otherwise it wouldn't work.

### CODE REVIEW

**Comment by Totto16** [comment]
CI failures are unrelated to this PR, macos-11 isn't available anymore as github runner, and the clang versions that fail are also not available anymore in the ubuntu runners 😓

**Comment by uilianries** [comment]
I'll send a new PR fixing the CI by today later.

**Comment by ColinH** [comment]
@uilianries Any update?

**Comment by uilianries** [comment]
@ColinH Sorry, totally missed it. I'm going to check it now.

**Comment by uilianries** [comment]
@ColinH Sorry the confusion, the PR #367 is the fix that I mentioned before. Just need a review to be merged.

**Comment by ColinH** [comment]
Is #367 the only PR that we need to merge now? In other words, did you incorporate the MSYS2 fixes into #367?

**Review by uilianries — APPROVED** [review]
LGTM. The CMake for this build will use Ninja by default.

Android build failed due a checksum mismatch, nothing related to this PR. Still, I would not block it due that failure.

**Comment by uilianries** [comment]
> Is #367 the only PR that we need to merge now? In other words, did you incorporate the MSYS2 fixes into #367?

Yes, I rebased those changes via the commit https://github.com/taocpp/PEGTL/pull/366/commits/8171fc48917a30fc259308336a0551e787b58c43

**Comment by Totto16** [comment]
Thank you @uilianries for your work ❤️

**Comment by Totto16** [comment]
@ColinH would it be possible to have new release, since now mysys2 is fully supported and works again?

**Comment by ColinH** [comment]
The `main` branch already has some changes towards a PEGTL 4.0 which I'm otherwise working towards on the `work` branch; the 4.0 with MSYS2 support will be released when it's ready.

**Pull request merged**
